apiVersion: v2
name: database
# This version number should be incremented each time you make changes to the chart and its templates
version: 0.1.0
description: A Helm chart for development database
type: application
keywords:
  - PostgreSQL 15.5
sources:
  - https://hub.docker.com/_/postgres/
maintainers:
  - name: Igor Vojinovic
    email: igor.vojinovic@cyberlab.rs
# This should follow release tag from luther code
appVersion: "1.0.0"
deprecated: false
