apiVersion: v1
kind: Service
metadata:
  name: {{ include "vote.fullname" . }}
  labels:
    {{- include "vote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  ipFamilies:
  {{- toYaml .Values.service.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - name: {{ include "vote.fullname" . }}
      port: {{ .Values.service.port }}
      targetPort: http-{{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "vote.selectorLabels" . | nindent 4 }}
